//! Real NIBS backend for the NIBSR prototype.
//!
//! This module replaces the earlier development-only Ed25519 transcript signer
//! with the SPS-EQ construction of NIBS from Hanzlik's paper:
//!
//!   KeyGen:  create SPS-EQ key (x1, x2), pk = (g2^x1, g2^x2)
//!   RKeyGen: choose sk_R = x, pk_R = g1^x
//!   Issue:   sign the representative (pk_R, H(nonce || authorization))
//!   Obtain:  adapt the signature by µ = sk_R^{-1}; output
//!            m = H(nonce || authorization)^{sk_R^{-1}}
//!   Verify:  verify the adapted SPS-EQ signature on (g1, m)
//!
//! For the revocable variant, the credential also carries a Chaum-Pedersen
//! DLEQ proof binding (pk_R, nonce, authorization) to m, so a verifier cannot
//! swap pk_R/nonce to bypass NIBSR.RevList.

use crate::encoding::{put_bytes, put_domain};
use crate::error::NibsrError;
use crate::types::{
    encode_authorization, Authorization, Credential, Nonce, Presignature, ReceiverPublicKey,
    SignerPublicKey, Tag,
};
use ark_bls12_381::{Bls12_381, Fr, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ec::{pairing::Pairing, AffineRepr, CurveGroup, Group};
use ark_ff::{Field, PrimeField, UniformRand, Zero};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use rand::rngs::OsRng;
use rand::RngCore;
use sha2::{Digest, Sha256, Sha512};
use std::io::Cursor;

const G1_COMPRESSED_BYTES: usize = 48;
const G2_COMPRESSED_BYTES: usize = 96;
const FR_COMPRESSED_BYTES: usize = 32;
const SPS_EQ_SIG_BYTES: usize = G1_COMPRESSED_BYTES + G1_COMPRESSED_BYTES + G2_COMPRESSED_BYTES;
const DLEQ_PROOF_BYTES: usize = G1_COMPRESSED_BYTES + G1_COMPRESSED_BYTES + FR_COMPRESSED_BYTES;
const FINAL_SIG_BYTES: usize = SPS_EQ_SIG_BYTES + DLEQ_PROOF_BYTES;
const SIGNER_PK_BYTES: usize = G2_COMPRESSED_BYTES * 2;

#[derive(Clone)]
pub struct SignerKeyPair {
    x1: Fr,
    x2: Fr,
    public: SignerPublicKey,
}

impl SignerKeyPair {
    /// Ham KeyGen: tao cap khoa cho Signer theo mo hinh SPS-EQ.
    #[allow(non_snake_case)]
    pub fn KeyGen() -> Self {
        Self::generate()
    }

    /// Sinh cap khoa signer (ten snake_case hien co).
    pub fn generate() -> Self {
        let mut rng = OsRng;
        let x1 = random_nonzero_scalar(&mut rng);
        let x2 = random_nonzero_scalar(&mut rng);
        let pk1 = G2Projective::generator() * x1;
        let pk2 = G2Projective::generator() * x2;

        let mut public = Vec::with_capacity(SIGNER_PK_BYTES);
        public.extend_from_slice(&g2_to_bytes(&pk1));
        public.extend_from_slice(&g2_to_bytes(&pk2));

        Self {
            x1,
            x2,
            public: SignerPublicKey(public),
        }
    }

    /// Lay khoa cong khai cua signer.
    pub fn public(&self) -> SignerPublicKey {
        self.public.clone()
    }
}

#[derive(Clone, Debug)]
pub struct ReceiverKeyPair {
    secret: Fr,
    public: ReceiverPublicKey,
}

impl ReceiverKeyPair {
    /// Ham RKeyGen: tao cap khoa cho Receiver.
    #[allow(non_snake_case)]
    pub fn RKeyGen() -> Self {
        Self::generate()
    }

    /// Sinh cap khoa receiver (ten snake_case hien co).
    pub fn generate() -> Self {
        let mut rng = OsRng;
        let secret = random_nonzero_scalar(&mut rng);
        let pk_r = G1Projective::generator() * secret;
        Self {
            secret,
            public: ReceiverPublicKey(g1_to_bytes(&pk_r)),
        }
    }

    /// Lay khoa cong khai cua receiver.
    pub fn public(&self) -> ReceiverPublicKey {
        self.public.clone()
    }

    /// Kiem tra khoa cong khai truyen vao co khop voi cap khoa nay hay khong.
    pub fn matches_public(&self, pk_r: &ReceiverPublicKey) -> bool {
        &self.public == pk_r
    }
}

/// Sinh nonce ngau nhien 32 byte.
pub fn random_nonce() -> Nonce {
    let mut nonce = [0u8; 32];
    let mut rng = OsRng;
    rng.fill_bytes(&mut nonce);
    nonce
}

pub struct SpsEqNibsBackend;

impl SpsEqNibsBackend {
    /// NIBSR.Issue(sk, pkR, nonce, auth).
    ///
    /// The authorization is hashed into the nonce transcript, so each temporary
    /// authorization scope/time/context gets a different NIBS message space.
    /// Ham issue ban snake_case.
    pub fn issue(
        signer: &SignerKeyPair,
        pk_r: ReceiverPublicKey,
        nonce: Nonce,
        auth: Authorization,
    ) -> Presignature {
        let pk_r_point = read_g1(&pk_r.0).expect("receiver public key generated by this crate");
        let h_nonce = hash_to_g1(&nonce, &auth);
        let sig = sign_eq(signer, &pk_r_point, &h_nonce);

        Presignature {
            signer_pk: signer.public(),
            pk_r,
            nonce,
            auth,
            bytes: sig.to_bytes(),
        }
    }

    /// Ham Issue theo dung ten trong tai lieu.
    #[allow(non_snake_case)]
    pub fn Issue(
        signer: &SignerKeyPair,
        pk_r: ReceiverPublicKey,
        nonce: Nonce,
        auth: Authorization,
    ) -> Presignature {
        Self::issue(signer, pk_r, nonce, auth)
    }

    /// NIBSR.Obtain(skR, pk, psig, nonce).
    /// Ham obtain ban snake_case.
    pub fn obtain(receiver: &ReceiverKeyPair, psig: Presignature) -> Result<Credential, NibsrError> {
        if !receiver.matches_public(&psig.pk_r) {
            return Err(NibsrError::ReceiverMismatch);
        }

        let pk_r_point = read_g1(&psig.pk_r.0)?;
        let signer_pk = parse_signer_pk(&psig.signer_pk)?;
        let h_nonce = hash_to_g1(&psig.nonce, &psig.auth);
        let presig = SpsEqSignature::from_bytes(&psig.bytes)?;

        if !verify_eq(&signer_pk, &pk_r_point, &h_nonce, &presig) {
            return Err(NibsrError::InvalidSignature);
        }

        let inv = receiver
            .secret
            .inverse()
            .ok_or(NibsrError::Malformed("zero receiver secret"))?;
        let nibs_message = h_nonce * inv;
        let adapted = change_rep_eq(&presig, inv);
        let nibs_message_bytes = g1_to_bytes(&nibs_message);
        let adapted_bytes = adapted.to_bytes();

        let proof = DleqProof::prove(
            receiver.secret,
            &pk_r_point,
            &nibs_message,
            &h_nonce,
            &psig.signer_pk,
            &psig.nonce,
            &psig.auth,
            &adapted_bytes,
        );

        let mut sigma = Vec::with_capacity(FINAL_SIG_BYTES);
        sigma.extend_from_slice(&adapted_bytes);
        sigma.extend_from_slice(&proof.to_bytes());

        let tag = compute_tag(
            &psig.signer_pk,
            &psig.pk_r,
            &psig.nonce,
            &psig.auth,
            &nibs_message_bytes,
            &sigma,
        );

        Ok(Credential {
            signer_pk: psig.signer_pk,
            pk_r: psig.pk_r,
            nonce: psig.nonce,
            auth: psig.auth,
            nibs_message: nibs_message_bytes,
            sigma,
            tag,
        })
    }

    /// Ham Obtain theo dung ten trong tai lieu.
    #[allow(non_snake_case)]
    pub fn Obtain(receiver: &ReceiverKeyPair, psig: Presignature) -> Result<Credential, NibsrError> {
        Self::obtain(receiver, psig)
    }

    /// Base cryptographic verification before the revocation lookup.
    /// Xac thuc nen tang ma hoa truoc khi doi chieu RevList.
    pub fn verify_base(cred: &Credential) -> Result<(), NibsrError> {
        if cred.sigma.len() != FINAL_SIG_BYTES {
            return Err(NibsrError::Malformed("wrong final signature length"));
        }

        let signer_pk = parse_signer_pk(&cred.signer_pk)?;
        let pk_r = read_g1(&cred.pk_r.0)?;
        let m = read_g1(&cred.nibs_message)?;
        let h_nonce = hash_to_g1(&cred.nonce, &cred.auth);

        let adapted = SpsEqSignature::from_bytes(&cred.sigma[..SPS_EQ_SIG_BYTES])?;
        let proof = DleqProof::from_bytes(&cred.sigma[SPS_EQ_SIG_BYTES..])?;

        let g1 = G1Projective::generator();
        if !verify_eq(&signer_pk, &g1, &m, &adapted) {
            return Err(NibsrError::InvalidSignature);
        }

        if !proof.verify(
            &pk_r,
            &m,
            &h_nonce,
            &cred.signer_pk,
            &cred.nonce,
            &cred.auth,
            &cred.sigma[..SPS_EQ_SIG_BYTES],
        ) {
            return Err(NibsrError::InvalidBindingProof);
        }

        let expected_tag = compute_tag(
            &cred.signer_pk,
            &cred.pk_r,
            &cred.nonce,
            &cred.auth,
            &cred.nibs_message,
            &cred.sigma,
        );
        if expected_tag != cred.tag {
            return Err(NibsrError::InvalidTag);
        }

        Ok(())
    }
}

/// τ = H("NIBSR/TAG" || pk || pkR || nonce || authorization || m || sigma).
/// Tinh tag thu hoi tu du lieu credential.
pub fn compute_tag(
    signer_pk: &SignerPublicKey,
    pk_r: &ReceiverPublicKey,
    nonce: &Nonce,
    auth: &Authorization,
    nibs_message: &[u8],
    sigma: &[u8],
) -> Tag {
    let mut payload = Vec::new();
    put_domain(&mut payload, "NIBSR/TAG/v2");
    put_bytes(&mut payload, &signer_pk.0);
    put_bytes(&mut payload, &pk_r.0);
    put_bytes(&mut payload, nonce);
    encode_authorization(&mut payload, auth);
    put_bytes(&mut payload, nibs_message);
    put_bytes(&mut payload, sigma);

    Sha256::digest(payload).into()
}

#[derive(Clone, Debug)]
struct SpsEqPublicKey {
    pk1: G2Affine,
    pk2: G2Affine,
}

#[derive(Clone, Debug)]
struct SpsEqSignature {
    z: G1Projective,
    y1: G1Projective,
    y2: G2Projective,
}

impl SpsEqSignature {
    /// Ma hoa chu ky SPS-EQ thanh bytes.
    fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(SPS_EQ_SIG_BYTES);
        out.extend_from_slice(&g1_to_bytes(&self.z));
        out.extend_from_slice(&g1_to_bytes(&self.y1));
        out.extend_from_slice(&g2_to_bytes(&self.y2));
        out
    }

    /// Giai ma bytes thanh chu ky SPS-EQ.
    fn from_bytes(bytes: &[u8]) -> Result<Self, NibsrError> {
        if bytes.len() != SPS_EQ_SIG_BYTES {
            return Err(NibsrError::Malformed("wrong SPS-EQ signature length"));
        }
        let z = read_g1(&bytes[0..G1_COMPRESSED_BYTES])?;
        let y1 = read_g1(&bytes[G1_COMPRESSED_BYTES..2 * G1_COMPRESSED_BYTES])?;
        let y2 = read_g2(&bytes[2 * G1_COMPRESSED_BYTES..SPS_EQ_SIG_BYTES])?;
        Ok(Self { z, y1, y2 })
    }
}

/// Ky SPS-EQ tren cap thong diep dai dien.
fn sign_eq(signer: &SignerKeyPair, m1: &G1Projective, m2: &G1Projective) -> SpsEqSignature {
    let mut rng = OsRng;
    let y = random_nonzero_scalar(&mut rng);
    let inv_y = y.inverse().expect("nonzero scalar has inverse");

    let base = (m1.clone() * signer.x1) + (m2.clone() * signer.x2);
    SpsEqSignature {
        z: base * y,
        y1: G1Projective::generator() * inv_y,
        y2: G2Projective::generator() * inv_y,
    }
}

/// Doi dai dien chu ky SPS-EQ theo he so mu.
fn change_rep_eq(sig: &SpsEqSignature, mu: Fr) -> SpsEqSignature {
    let mut rng = OsRng;
    let psi = random_nonzero_scalar(&mut rng);
    let inv_psi = psi.inverse().expect("nonzero scalar has inverse");

    SpsEqSignature {
        z: sig.z.clone() * (psi * mu),
        y1: sig.y1.clone() * inv_psi,
        y2: sig.y2.clone() * inv_psi,
    }
}

/// Kiem tra chu ky SPS-EQ bang phep pairing.
fn verify_eq(pk: &SpsEqPublicKey, m1: &G1Projective, m2: &G1Projective, sig: &SpsEqSignature) -> bool {
    let left = Bls12_381::multi_pairing(
        [m1.clone().into_affine(), m2.clone().into_affine()],
        [pk.pk1.clone(), pk.pk2.clone()],
    );
    let right = Bls12_381::pairing(sig.z.clone().into_affine(), sig.y2.clone().into_affine());

    let y_relation_left = Bls12_381::pairing(sig.y1.clone().into_affine(), G2Projective::generator().into_affine());
    let y_relation_right = Bls12_381::pairing(G1Projective::generator().into_affine(), sig.y2.clone().into_affine());

    left == right && y_relation_left == y_relation_right
}

#[derive(Clone, Debug)]
struct DleqProof {
    a1: G1Projective,
    a2: G1Projective,
    s: Fr,
}

impl DleqProof {
    /// Tao bang chung DLEQ rang buoc pkR voi thong diep NIBS cuoi.
    fn prove(
        secret: Fr,
        pk_r: &G1Projective,
        m: &G1Projective,
        h_nonce: &G1Projective,
        signer_pk: &SignerPublicKey,
        nonce: &Nonce,
        auth: &Authorization,
        adapted_signature: &[u8],
    ) -> Self {
        let mut rng = OsRng;
        let r = random_nonzero_scalar(&mut rng);
        let a1 = G1Projective::generator() * r;
        let a2 = m.clone() * r;
        let c = dleq_challenge(&a1, &a2, pk_r, m, h_nonce, signer_pk, nonce, auth, adapted_signature);
        let s = r + c * secret;
        Self { a1, a2, s }
    }

    /// Xac minh bang chung DLEQ.
    fn verify(
        &self,
        pk_r: &G1Projective,
        m: &G1Projective,
        h_nonce: &G1Projective,
        signer_pk: &SignerPublicKey,
        nonce: &Nonce,
        auth: &Authorization,
        adapted_signature: &[u8],
    ) -> bool {
        let c = dleq_challenge(&self.a1, &self.a2, pk_r, m, h_nonce, signer_pk, nonce, auth, adapted_signature);
        let left1 = G1Projective::generator() * self.s;
        let right1 = self.a1.clone() + (pk_r.clone() * c);
        let left2 = m.clone() * self.s;
        let right2 = self.a2.clone() + (h_nonce.clone() * c);
        left1 == right1 && left2 == right2
    }

    /// Ma hoa DLEQ proof thanh bytes.
    fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(DLEQ_PROOF_BYTES);
        out.extend_from_slice(&g1_to_bytes(&self.a1));
        out.extend_from_slice(&g1_to_bytes(&self.a2));
        out.extend_from_slice(&fr_to_bytes(&self.s));
        out
    }

    /// Giai ma bytes thanh DLEQ proof.
    fn from_bytes(bytes: &[u8]) -> Result<Self, NibsrError> {
        if bytes.len() != DLEQ_PROOF_BYTES {
            return Err(NibsrError::Malformed("wrong DLEQ proof length"));
        }
        let a1 = read_g1(&bytes[0..G1_COMPRESSED_BYTES])?;
        let a2 = read_g1(&bytes[G1_COMPRESSED_BYTES..2 * G1_COMPRESSED_BYTES])?;
        let s = read_fr(&bytes[2 * G1_COMPRESSED_BYTES..DLEQ_PROOF_BYTES])?;
        Ok(Self { a1, a2, s })
    }
}

/// Tao challenge cho giao thuc Chaum-Pedersen DLEQ.
fn dleq_challenge(
    a1: &G1Projective,
    a2: &G1Projective,
    pk_r: &G1Projective,
    m: &G1Projective,
    h_nonce: &G1Projective,
    signer_pk: &SignerPublicKey,
    nonce: &Nonce,
    auth: &Authorization,
    adapted_signature: &[u8],
) -> Fr {
    let mut payload = Vec::new();
    put_domain(&mut payload, "NIBSR/DLEQ/CHAUM-PEDERSEN/v1");
    put_bytes(&mut payload, &signer_pk.0);
    put_bytes(&mut payload, nonce);
    encode_authorization(&mut payload, auth);
    put_bytes(&mut payload, &g1_to_bytes(pk_r));
    put_bytes(&mut payload, &g1_to_bytes(m));
    put_bytes(&mut payload, &g1_to_bytes(h_nonce));
    put_bytes(&mut payload, &g1_to_bytes(a1));
    put_bytes(&mut payload, &g1_to_bytes(a2));
    put_bytes(&mut payload, adapted_signature);
    hash_to_scalar(&payload)
}

/// Phan tich khoa cong khai signer tu bytes.
fn parse_signer_pk(pk: &SignerPublicKey) -> Result<SpsEqPublicKey, NibsrError> {
    if pk.0.len() != SIGNER_PK_BYTES {
        return Err(NibsrError::InvalidPublicKey);
    }
    let pk1 = read_g2_affine(&pk.0[0..G2_COMPRESSED_BYTES])?;
    let pk2 = read_g2_affine(&pk.0[G2_COMPRESSED_BYTES..SIGNER_PK_BYTES])?;
    Ok(SpsEqPublicKey { pk1, pk2 })
}

/// Bam (nonce, auth) thanh diem G1.
fn hash_to_g1(nonce: &Nonce, auth: &Authorization) -> G1Projective {
    let mut payload = Vec::new();
    put_domain(&mut payload, "NIBSR/SPS-EQ/HASH-TO-G1/v1");
    put_bytes(&mut payload, nonce);
    encode_authorization(&mut payload, auth);
    let scalar = hash_to_nonzero_scalar(&payload);
    G1Projective::generator() * scalar
}

/// Bam du lieu thanh scalar khac 0.
fn hash_to_nonzero_scalar(data: &[u8]) -> Fr {
    let mut counter = 0u64;
    loop {
        let mut h = Sha512::new();
        h.update(b"NIBSR/HASH-TO-SCALAR/v1");
        h.update(counter.to_be_bytes());
        h.update(data);
        let digest = h.finalize();
        let s = Fr::from_le_bytes_mod_order(&digest[..]);
        if !s.is_zero() {
            return s;
        }
        counter += 1;
    }
}

/// Bam du lieu thanh scalar (co the bang 0).
fn hash_to_scalar(data: &[u8]) -> Fr {
    let digest = Sha512::digest(data);
    Fr::from_le_bytes_mod_order(&digest[..])
}

/// Sinh scalar ngau nhien khac 0.
fn random_nonzero_scalar(rng: &mut OsRng) -> Fr {
    loop {
        let s = Fr::rand(rng);
        if !s.is_zero() {
            return s;
        }
    }
}

/// Ma hoa diem G1 thanh compressed bytes.
fn g1_to_bytes(p: &G1Projective) -> Vec<u8> {
    let mut out = Vec::new();
    p.clone().into_affine()
        .serialize_compressed(&mut out)
        .expect("G1 serialization cannot fail for Vec");
    out
}

/// Ma hoa diem G2 thanh compressed bytes.
fn g2_to_bytes(p: &G2Projective) -> Vec<u8> {
    let mut out = Vec::new();
    p.clone().into_affine()
        .serialize_compressed(&mut out)
        .expect("G2 serialization cannot fail for Vec");
    out
}

/// Ma hoa scalar Fr thanh compressed bytes.
fn fr_to_bytes(s: &Fr) -> Vec<u8> {
    let mut out = Vec::new();
    s.serialize_compressed(&mut out)
        .expect("Fr serialization cannot fail for Vec");
    out
}

/// Doc compressed bytes thanh diem G1.
fn read_g1(bytes: &[u8]) -> Result<G1Projective, NibsrError> {
    let mut cursor = Cursor::new(bytes);
    let affine = G1Affine::deserialize_compressed(&mut cursor).map_err(|_| NibsrError::InvalidPublicKey)?;
    Ok(affine.into_group())
}

/// Doc compressed bytes thanh diem G2.
fn read_g2(bytes: &[u8]) -> Result<G2Projective, NibsrError> {
    let affine = read_g2_affine(bytes)?;
    Ok(affine.into_group())
}

/// Doc compressed bytes thanh diem G2 affine.
fn read_g2_affine(bytes: &[u8]) -> Result<G2Affine, NibsrError> {
    let mut cursor = Cursor::new(bytes);
    G2Affine::deserialize_compressed(&mut cursor).map_err(|_| NibsrError::InvalidPublicKey)
}

/// Doc compressed bytes thanh scalar Fr.
fn read_fr(bytes: &[u8]) -> Result<Fr, NibsrError> {
    let mut cursor = Cursor::new(bytes);
    Fr::deserialize_compressed(&mut cursor).map_err(|_| NibsrError::Malformed("invalid scalar"))
}
